### ISSUE TITLE
Debian sid eth0 renaming

### ISSUE THREAD

**Issue by osallou** [andsens/bootstrap-vz#245] opened 2015-08-14 12:58 UTC
Hi,
I tried to create a virtualbox image for Debian sid, but I face an issue with the network interface name.

Indeed, ssh etc.. fails. When looking at interfaces, eth0 is not up, and does not exists in fact.
A ifconfig -a gives an interface named enp0s3, not eth0. This seems related to recent udev versions.

In bootstrap-vz/bootstrapvz/common/tasks/network-configuration.yml , it may be as simple as using this interface name instead of eth0, but I do not know if this is an absolute/fixed name in all cases....
I found many posts on subject but no clear explanation.

**Comment by andsens** [comment] 2015-08-16 09:01
Hm. I think we need to research this a little further before doing anything. Which version of VirtualBox are you using? Maybe it's because of the recent 5.0 update?

**Comment by osallou** [comment] 2015-08-16 09:18
I use version 4.3.10
But this is not virtualbox issue but Debian sid (and other distrib) network packages update, renaming interface following a new scheme.
Goal is to get reproductible network interface assignment.

**Comment by andsens** [comment] 2015-08-16 11:17
Somehow I managed to read around the "sid" part. Now it makes more sense :-)  
Do you think the IF names will stay like that? In that case it's obviously quite easy to fix it.

**Comment by osallou** [comment] 2015-08-16 11:41
For the eth0 equivalent it seems so, but I am not sure.

If fixed, fixing is indeed really easy, but I am not confident enough to know if it will match all situations.
A possiblity would be to use this as "default" but be able via the manifest to specify it.

**Comment by andsens** [comment] 2015-08-16 11:56
> A possiblity would be to use this as "default" but be able via the manifest to specify it.

That'd be outsourcing problems to the user, I don't like that very much. When bootstrapping we have all the information to figure out what the IFs will be called. All that is needed is some research - I'll check it out when I have some time.

**Comment by myhro** [comment] 2015-08-16 12:55
Olivier,

Do you think that this isn't related to the kernel version? Looks like `sid` is running Linux 4.1. My laptop (Xubuntu 14.04) is running a 3.13 kernel and its Ethernet device is named `p10p1`. My `jessie` server is running the default 3.16 kernel and it is still named `eth0`.

**Comment by osallou** [comment] 2015-08-16 12:59
Kernel or related network packages.
Udev rename interface following a defined scheme, related to type of interface, card slot etc... So it may differ. And at boostrap image generation, we cannot know for sure the network interface name. But i do not master the subject.

**Comment by myhro** [comment] 2015-08-16 14:02
Well, this is indeed related to [Predictable Network Interface Names][1] in sytemd/udev. What is still confusing to me is that if the `s` on `enp0s3` [means slot][2], how can we be sure if it will be `0`, `3` or anything else on VirtualBox (not to mention other platforms)?

As bootstrap-vz doesn't support multiple network interfaces (IIRC), we can do something like grabbing the [name of the first symlink][3] that isn't `lo` on `/sys/class/net/` - at least until we figure out how this should be done.

[1]: https://wiki.freedesktop.org/www/Software/systemd/PredictableNetworkInterfaceNames/
[2]: http://cgit.freedesktop.org/systemd/systemd/tree/src/udev/udev-builtin-net_id.c#n20
[3]: http://fossdev.blogspot.com.br/2011/07/fedora-15-wired-network-interface-named.html

**Comment by osallou** [comment] 2015-08-16 14:39
For virtualbox, I think we can suppose it will always be the same enp0s3, but other providers we cannot know for sure

**Comment by andsens** [comment] 2015-08-16 18:12
> As bootstrap-vz doesn't support multiple network interfaces (IIRC)

After the merge with `JamesBromberger/bootstrap-vz` we actually support multiple ENIs on EC2 now.

**Comment by srivasta** [comment] 2015-09-29 20:24
For what it is worth, the same issue exists qith qemu/kvm images on Debian Sid

**Comment by srivasta** [comment] 2015-09-30 21:57
ifconfig -a
ens3: flags=4098<BROADCAST,MULTICAST>   mtu 1500
         ether 52:54:00:23:bf:36  txqueuelen 1000 (Ethernet)
         RX packets 0 bytes 0 (0.0 B)
         RX Errors 0 dropped 0 overruns 0 frame 0
         TX packets 0 bytes 0 (0.0 B)
         TX Errors 0 dropped 0 overruns 0 carrier 0 collisions 0

**Comment by apolloclark** [comment] 2016-01-29 13:46
Predictable Network Interface Names can be disabled, using a grub command:

```Shell
GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
```

http://askubuntu.com/questions/628217/use-of-predictable-network-interface-names-with-alternate-kernels

I'll publish a pull request with this change, adding it as an option in the manifest.

**Comment by andsens** [comment] 2016-01-29 14:15
Thanks for the link. Compared to the other solutions, this seems like the most sensible and forward compatible way to do it (any comments @osallou?).

**Comment by osallou** [comment] 2016-01-29 14:24
this looks fine indeed. I do not have time to test for the moment however

**Comment by osallou** [comment] 2016-01-29 14:25
but a more long term solution should be found i think, while keeping this workaround

**Comment by apolloclark** [comment] 2016-01-29 18:41
I create a pull request:
https://github.com/andsens/bootstrap-vz/pull/276

This isn't 100% functional. It still requires running "sudo update-grub" after booting the instance in Virtualbox. Any ideas?

**Comment by apolloclark** [comment] 2016-01-30 04:29
I updated the pull request, added documentation, fixed whitespace issues. I can confirm this fix works with Jessie, and enables Stretch. However, in Virtualbox, the user still needs to run "update-grub" upon first boot. Any ideas?

**Comment by apolloclark** [comment] 2016-01-30 14:26
Ok, I got it working, by moving the "update-grub" command to happen after changing the grub config file. I can confirm this works for Debian Stretch and Jessie on Virtualbox.

https://github.com/andsens/bootstrap-vz/pull/276

I'll do some testing tomorrow to add compatibility with Amazon and Azure providers.

**Comment by nbraud** [comment] 2016-08-13 23:00
Should this issue be closed?
As far as I can see, building `sid` images works fine.

(If it is still there to track the need to remove the hack and support predictable if names, then please rename the issue)

**Comment by andsens** [comment] 2016-08-14 07:54
Yup, closing. #276 fixed this, though currently we deviate quite a bit from standard Debian on this. At some point we will need to figure out an alternative solution that aligns more with the default config.

**Closed by andsens** 2016-08-14 07:54 UTC
Labels: bug, VirtualBox
