### ISSUE TITLE
Corrupt manifest for S3

### ISSUE THREAD

**Issue by eugenea** [andsens/bootstrap-vz#29] opened 2014-03-07 01:22 UTC
<Response><Errors><Error><Code>InvalidManifest</Code><Message>Invalid AMI manifest</Message></Error>

Cant tell what is wrong with manifest, looks ok to me but amazont won't accept it.

**Comment by jszwedko** [comment] 2015-03-26 05:12
The manifest appears to be valid when using version `3.2.0` (and master) of `euca2ools`.

**Comment by andsens** [comment] 2015-04-10 06:27
Closing since it really is a duplicate of #27

**Closed by andsens** 2015-04-10 06:27 UTC
Labels: bug, EC2
