### ISSUE TITLE
parted refuse to create the last partition

### ISSUE THREAD

**Issue by vincentbernat** [andsens/bootstrap-vz#127] opened 2014-07-29 09:21 UTC
Hi!

Using `kvm-virtio.manifest.yml`, building an image fails with the following output:

```
Creating a loopback volume
Executing: qemu-img create -f raw /target/39b141ce/volume.raw 1024M
Formatting '/target/39b141ce/volume.raw', fmt=raw size=1073741824
Attaching the volume
Executing: losetup --show --find /target/39b141ce/volume.raw
/dev/loop0
Partitioning the volume
Executing: parted --script --align none /dev/loop0 -- mklabel msdos
Executing: parted --script --align none /dev/loop0 -- mkpart primary 2MiB 32MiB
Executing: parted --script /dev/loop0 -- set 1 boot on
Executing: parted --script --align none /dev/loop0 -- mkpart primary 32MiB 160MiB
Executing: parted --script --align none /dev/loop0 -- mkpart primary 160MiB 1GiB
Error: The location 1GiB is outside of the device /dev/loop0.
Command 'parted --script --align none /dev/loop0 -- mkpart primary 160MiB 1GiB' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/main.py", line 96, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
    task.run(info)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/common/tasks/partitioning.py", line 27, in run
    info.volume.partition_map.create(info.volume)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 50, in create
    self.fsm.create(volume=volume)
  File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 178, in fn
    if self._before_event(e) is False:
  File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 208, in _before_event
    return getattr(self, fnname)(e)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/msdos.py", line 64, in _before_create
    partition.create(volume)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/fs/partitions/base.py", line 43, in create
    self.fsm.create(volume=volume)
  File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 178, in fn
    if self._before_event(e) is False:
  File "/usr/lib/python2.7/dist-packages/fysom/__init__.py", line 208, in _before_event
    return getattr(self, fnname)(e)
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/fs/partitions/base.py", line 88, in _before_create
    '--', create_command])
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/common/tools.py", line 8, in log_check_call
    raise CalledProcessError(status, ' '.join(command), '\n'.join(stderr))
CalledProcessError: Command 'parted --script --align none /dev/loop0 -- mkpart primary 160MiB 1GiB' returned non-zero exit status 1
Rolling back
Tasklist:
        bootstrapvz.common.tasks.volume.Detach
        bootstrapvz.common.tasks.volume.Delete
        bootstrapvz.common.tasks.workspace.DeleteWorkspace
Detaching the volume
Executing: losetup --detach /dev/loop0
Deleting the volume
Deleting workspace
Successfully completed rollback
Traceback (most recent call last):
  File "./bootstrap-vz", line 5, in <module>
    main()
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/main.py", line 31, in main
    dry_run=opts['--dry-run'])
  File "/home/bernat/code/exoscale/bootstrap-vz/bootstrapvz/base/main.py", line 128, in run
    raise e
subprocess.CalledProcessError: Command 'parted --script --align none /dev/loop0 -- mkpart primary 160MiB 1GiB' returned non-zero exit status 1
```

I am on an up-to-date sid. parted is 3.1-4.

**Comment by EmmanuelKasper** [comment] 2015-01-15 11:28
As @vincentbernat said:

The following command sequences 
```
qemu-img create -f raw test.raw 1024M
losetup --show --find test.raw
parted --script --align none /dev/loop0 -- mklabel msdos
parted --script --align none /dev/loop0 -- mkpart primary 160MiB 1GiB
```
works on Debian 7 (parted 2.3) but fails on Debian 8 ( parted 3.2) with the message:
    Error: The location 1GiB is outside of the device /dev/loop0

This is either a regression in libparted, or maybe we use here some unsupported calculations in parted.

**Comment by EmmanuelKasper** [comment] 2015-01-15 11:34
Since this bug renders bootstrap-vz unusable on a Debian 8 host, would you maybe consider the pull request of @andrewbogott ?

**Comment by andsens** [comment] 2015-04-28 14:35
This is fixed in dev. I have converted all units into sectors and introduced partition gaps now.

**Comment by hashar** [comment] 2015-04-28 20:04
Thank you @andsens !

**Closed** 2015-05-02 20:42 UTC
Labels: bug, fixed in dev
