### ISSUE TITLE
Can't build for jessie in either master or development branch

### ISSUE THREAD

**Issue by pmorch** [andsens/bootstrap-vz#155] opened 2014-11-20 15:01 UTC
I've started with a fresh jessie image [described here](https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie):

Then I:

    apt-get update
    apt-get install parted kpartx debootstrap python-pip git vim-gtk
    pip install termcolor jsonschema fysom boto docopt
    pip install boto --upgrade
    git clone https://github.com/andsens/bootstrap-vz.git

And ran

    AWS_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX AWS_SECRET_KEY=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY ./bootstrap-vz <manifestfile>

On both master and development for both wheezy and jessie.

Wheezy worked in both master and development and jessie failed in both.

master jessie error:

    ....
    Upgrading packages and fixing broken dependencies
    Installing packages
    E: Package 'dhcpcd' has no installation candidate
    apt exited with status code 100. This can sometimes occur when package retrieval times out or a package extraction failed. apt might succeed if you try bootstrapping again.
    Command 'chroot /target/e49e1a80/root apt-get install --no-install-recommends --assume-yes grub-pc cloud-init sudo file dhcpcd linux-image-amd64 openssh-server' returned non-zero exit status 100
    Traceback (most recent call last):
      File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 78, in run
        tasklist.run(info=bootstrap_info, dry_run=opts['--dry-run'])
      File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
        task.run(info)
      File "/root/bootstrap-vz/bootstrapvz/common/tasks/packages.py", line 38, in run
        actions[package.__class__](info, batch)
      File "/root/bootstrap-vz/bootstrapvz/common/tasks/packages.py", line 73, in install_remote
        raise e
    CalledProcessError: Command 'chroot /target/e49e1a80/root apt-get install --no-install-recommends --assume-yes grub-pc cloud-init sudo file dhcpcd linux-image-amd64 openssh-server' returned non-zero exit status 100
    Rolling back
    ....

development jessie error:

    ....
    Adding 'diversion of /etc/init/ureadahead.conf to /etc/init/ureadahead.conf.disabled by cloud-init'
    df: Warning: cannot read table of mounted file systems: No such file or directory
    Disabling getty processes
    [Errno 2] No such file or directory
    Traceback (most recent call last):
      File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
        tasklist.run(info=bootstrap_info, dry_run=dry_run)
      File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
        task.run(info)
      File "/root/bootstrap-vz/bootstrapvz/common/tasks/boot.py", line 31, in run
        sed_i(inittab_path, '^' + tty1, '#' + tty1)
      File "/root/bootstrap-vz/bootstrapvz/common/tools.py", line 62, in sed_i
        for line in fileinput.input(files=file_path, inplace=True):
      File "/usr/lib/python2.7/fileinput.py", line 252, in next
        line = self.readline()
      File "/usr/lib/python2.7/fileinput.py", line 321, in readline
        os.rename(self._filename, self._backupfilename)
    OSError: [Errno 2] No such file or directory
    Rolling back
    ....

Details in https://gist.github.com/pmorch/c490699506ffc8d71c01

**Comment by andsens** [comment] 2015-01-02 13:56
The `wip-integration-testing` branch now has quite a few fixes for jessie. Could I get you guys to test it?  
I am still having trouble with booting: Somehow the kernel is unable to find `fsck.ext4` and there are two bug reports concerning this problem in the Debian bugtracker:  
[vmdebootstrap should install kernel last](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764596) & [sysvinit-utils: sulogin segfault](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763869).

The former suggests re-running `update-initramfs -u`, though that doesn't help. If anybody has a suggestion on how to fix this, it would very much appreciated.

**Comment by Rory-Finnegan** [comment] 2015-01-02 21:27
So, I when I try to build an image using the latest revision of `wip-integration-testing` I get: 
```
Loading provider bootstrapvz.providers.ec2
Traceback (most recent call last):
  File "bootstrap-vz", line 5, in <module>
    main()
  File "bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "bootstrap-vz/bootstrapvz/base/main.py", line 103, in run
    bootstrap_info = BootstrapInformation(manifest=manifest, debug=debug)
  File "bootstrap-vz/bootstrapvz/base/bootstrapinfo.py", line 29, in __init__
    self.volume = load_volume(self.manifest.volume, manifest.system['bootloader'])
  File "bootstrap-vz/bootstrapvz/base/fs/__init__.py", line 41, in load_volume
    return volume_backing(partition_map)
  File "bootstrap-vz/bootstrapvz/base/fs/volume.py", line 33, in __init__
    self.size = self.partition_map.get_total_size()
  File "bootstrap-vz/bootstrapvz/base/fs/partitionmaps/none.py", line 36, in get_total_size
    return self.root.get_end()
  File "bootstrap-vz/bootstrapvz/base/fs/partitions/abstract.py", line 58, in get_end
    return self.get_start() + self.size
  File "bootstrap-vz/bootstrapvz/common/bytes.py", line 8, in check_other
    raise UnitError(msg)
bootstrapvz.common.exceptions.UnitError: Can only add Bytes to Bytes
```
This is just while trying to build with the `ec2-ebs-debian-testing-amd64-pvm.manifest.yml` manifest. Looking at the log it seems like this [commit](https://github.com/andsens/bootstrap-vz/commit/4cb09c19a1c78dbe3c3754c832d74d76fe45b354) is where the change happened. If I have time later today I'll try to fix this myself.

**Comment by andsens** [comment] 2015-01-03 01:01
I have recently changed the size of the volumes from bytes to sectors, the addition should however work because both `get_start()` and `self.size` should be `Sectors`. I 'll check it out tomorrow.

**Comment by andrewbogott** [comment] 2015-01-05 05:54
On Jessie the wip-integration-testing branch fails for me like this:

Error: You requested a partition from 1049kB to 10.7GB (sectors 2048..20971519).
The closest location we can manage is 1049kB to 10.7GB (sectors 2049..20971486).
Command 'parted --script --align none /dev/loop0 -- mkpart primary 2048s 20971519s' returned non-zero exit status 1

**Comment by andsens** [comment] 2015-01-05 07:33
Man... parted definitely changed things up when it comes to disk locations, almost like the decided to start measuring from 1 instead of 0. Could you post the manifest, or is it one of the standard ones? So far I have only tested with virtualbox and kpartx is currently acting up on jessie.

**Comment by andrewbogott** [comment] 2015-01-05 07:37
With the standard manifest kvm.manifest.yml I get a similar failure:  

Error: You requested a partition from 33.6MB to 168MB (sectors 65536..327680).
The closest location we can manage is 33.6MB to 168MB (sectors 65537..327680).
Command 'parted --script --align none /dev/loop0 -- mkpart primary 65536s 327680s' returned non-zero exit status 1

So, should be easy for you to reproduce :(

**Comment by andsens** [comment] 2015-01-17 11:50
Try giving the `wip-integration-testing` a spin. My jessie unit tests (for virtualbox at least) all succeed now.

**Comment by Rory-Finnegan** [comment] 2015-01-17 21:09
Works great now, thanks!

**Comment by andrewbogott** [comment] 2015-01-23 22:50
Yep, the partition bug looks fixed.  Now I'm getting a few of these:

  df: Warning: cannot read table of mounted file systems: No such file or directory

Would you like me to open a new issue for that, or is that something known and/or unimportant?

**Comment by andsens** [comment] 2015-01-24 00:42
It's inconsequential, no reason to open a ticket. Someday it'll probably annoy me enough for me to dig in, debug, and fix it :-)

**Comment by ssgelm** [comment] 2015-03-28 21:22
@andsens I believe the df warning can be fixed by copying /proc/mounts into /etc/mtab in the chroot.

**Comment by andsens** [comment] 2015-03-29 10:38
@ssgelm alright, I'll definitely try that.

**Comment by myhro** [comment] 2015-04-26 05:23
I've thought this was solved, but now I'm getting `CalledProcessError: Command 'chroot /target/cf2f3405/root grub-install /dev/dm-0' returned non-zero exit status 1` on both `test_msdos_grub_stable` and `test_gpt_grub_stable`. :-(

**Comment by andsens** [comment] 2015-04-26 08:41
> Edit: I guess that's because jessie was released yesterday, so now stable points to it.

Whoa! There we go I guess :-)
I updated the codename mapping accordingly: d1197ca82cc347dd6b0ab0e8aaa48e60325c4048
Could you try again?

**Comment by myhro** [comment] 2015-04-26 15:06
I almost didn't believed that all errors that were popping (including `OSError: [Errno 2] No such file or directory`) were caused by the outdated codename mapping. Everything is fine now:

```
tests.integration.virtualbox_tests.test_unpartitioned_extlinux_oldstable ... ok
tests.integration.virtualbox_tests.test_msdos_extlinux_oldstable ... ok
tests.integration.virtualbox_tests.test_gpt_extlinux_oldstable ... ok
tests.integration.virtualbox_tests.test_unpartitioned_extlinux_stable ... ok
tests.integration.virtualbox_tests.test_msdos_extlinux_stable ... ok
tests.integration.virtualbox_tests.test_gpt_extlinux_stable ... ok
tests.integration.virtualbox_tests.test_msdos_grub_stable ... ok
tests.integration.virtualbox_tests.test_gpt_grub_stable ... ok
tests.integration.virtualbox_tests.test_unpartitioned_extlinux_unstable ... ok
tests.integration.virtualbox_tests.test_msdos_extlinux_unstable ... ok
tests.integration.virtualbox_tests.test_gpt_extlinux_unstable ... ok
tests.integration.virtualbox_tests.test_msdos_grub_unstable ... ok
tests.integration.virtualbox_tests.test_gpt_grub_unstable ... ok
```

Thank you, Anders! Can we mark it as `fixed in dev` now? :-)

**Comment by andsens** [comment] 2015-04-26 15:18
Sweet! Good to hear. I marked it.

**Closed** 2015-05-02 20:42 UTC
Labels: fixed in dev, jessie
